export { default as App } from "./App.tsx";
export { default as routes } from "./Routers/routes.tsx";
export { AboutTemplate } from "./Template/AboutTemplate.tsx";
export { HomeTemplate } from "./Template/HomeTemplate.tsx";
export { Dashboard } from "./components/Dashboard.jsx";
export { Login } from "./components/Login.jsx";
export { Navbar } from "./components/Navbar.jsx";
export { ProtectedRoute } from "./components/ProtectedRoute.jsx";
export { Register } from "./components/Register.jsx";
export { useAuth, AuthProvider } from "./context/AuthContext.jsx";
export { VerifyEmail } from "./context/VerifyEmail.jsx";
export { app, auth } from "./firebase/firebase.jsx";
export { PageNotFound } from "./pages/404.tsx";
export { About } from "./pages/About.tsx";
export { Home } from "./pages/Home.tsx";
